# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sobtracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sobtracker
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'

  target 'sobtrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sobtracker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sobtracker-tvOS

  target 'sobtracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
